package com.meshtastic.client.lua;

/**
 * Lua canvas event delivered to {@code on_canvas_event(event)} or
 * {@code on_canvas_frame(event)}.
 */
public record LuaCanvasEvent(String type,
                             double x,
                             double y,
                             double screenX,
                             double screenY,
                             String button,
                             int clickCount,
                             boolean primaryDown,
                             boolean middleDown,
                             boolean secondaryDown,
                             double wheelDeltaX,
                             double wheelDeltaY,
                             String code,
                             String key,
                             String text,
                             boolean shiftDown,
                             boolean controlDown,
                             boolean altDown,
                             boolean metaDown,
                             double width,
                             double height,
                             double timeSeconds,
                             double deltaSeconds) {

    public static LuaCanvasEvent mouse(String type,
                                       double x,
                                       double y,
                                       double screenX,
                                       double screenY,
                                       String button,
                                       int clickCount,
                                       boolean primaryDown,
                                       boolean middleDown,
                                       boolean secondaryDown,
                                       double width,
                                       double height) {
        return new LuaCanvasEvent(
                type,
                x,
                y,
                screenX,
                screenY,
                button != null ? button : "",
                clickCount,
                primaryDown,
                middleDown,
                secondaryDown,
                0,
                0,
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                width,
                height,
                nowSeconds(),
                0);
    }

    public static LuaCanvasEvent scroll(double x,
                                        double y,
                                        double screenX,
                                        double screenY,
                                        double deltaX,
                                        double deltaY,
                                        double width,
                                        double height) {
        return new LuaCanvasEvent(
                "scroll",
                x,
                y,
                screenX,
                screenY,
                "",
                0,
                false,
                false,
                false,
                deltaX,
                deltaY,
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                width,
                height,
                nowSeconds(),
                0);
    }

    public static LuaCanvasEvent key(String type,
                                     String code,
                                     String key,
                                     String text,
                                     boolean shiftDown,
                                     boolean controlDown,
                                     boolean altDown,
                                     boolean metaDown,
                                     double width,
                                     double height) {
        return new LuaCanvasEvent(
                type,
                0,
                0,
                0,
                0,
                "",
                0,
                false,
                false,
                false,
                0,
                0,
                code != null ? code : "",
                key != null ? key : "",
                text != null ? text : "",
                shiftDown,
                controlDown,
                altDown,
                metaDown,
                width,
                height,
                nowSeconds(),
                0);
    }

    public static LuaCanvasEvent frame(double width, double height, double deltaSeconds) {
        return new LuaCanvasEvent(
                "frame",
                0,
                0,
                0,
                0,
                "",
                0,
                false,
                false,
                false,
                0,
                0,
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                width,
                height,
                nowSeconds(),
                deltaSeconds);
    }

    public static LuaCanvasEvent simple(String type, double width, double height) {
        return new LuaCanvasEvent(
                type,
                0,
                0,
                0,
                0,
                "",
                0,
                false,
                false,
                false,
                0,
                0,
                "",
                "",
                "",
                false,
                false,
                false,
                false,
                width,
                height,
                nowSeconds(),
                0);
    }

    private static double nowSeconds() {
        return System.currentTimeMillis() / 1000.0;
    }
}
