package com.meshtastic.client.rpc;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Base64;
import java.util.Objects;

/**
 * Shared secret used to authenticate direct RPC peers, derive encrypted direct
 * sessions, and later derive router room identifiers.
 *
 * @author Konstantin A. Smirnov (ks@privatepractice.app)
 */
public final class RpcAccessKey {

    private static final String PREFIX = "mra1_";
    private static final int KEY_BYTES = 32;
    private static final int NONCE_BYTES = 24;
    private static final String ROOM_ID_PREFIX = "erpc1_";
    private static final byte[] ROOM_ID_CONTEXT = "ERPC-Router room id v1".getBytes(java.nio.charset.StandardCharsets.UTF_8);
    private static final byte[] CLIENT_PROOF_CONTEXT = "meshapp-rpc-client-auth-v2".getBytes(java.nio.charset.StandardCharsets.UTF_8);
    private static final byte[] SERVER_PROOF_CONTEXT = "meshapp-rpc-server-auth-v2".getBytes(java.nio.charset.StandardCharsets.UTF_8);
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final Base64.Encoder ENCODER = Base64.getUrlEncoder().withoutPadding();
    private static final Base64.Decoder DECODER = Base64.getUrlDecoder();

    private final String value;
    private final byte[] keyBytes;

    private RpcAccessKey(String value, byte[] keyBytes) {
        this.value = value;
        this.keyBytes = keyBytes;
    }

    /**
     * Generates a new random access key suitable for showing on MeshApp Host.
     *
     * @return generated access key
     */
    public static RpcAccessKey generate() {
        byte[] bytes = new byte[KEY_BYTES];
        SECURE_RANDOM.nextBytes(bytes);
        return new RpcAccessKey(PREFIX + ENCODER.encodeToString(bytes), bytes);
    }

    /**
     * Parses an access key string.
     *
     * @param value key text
     * @return parsed key
     */
    public static RpcAccessKey parse(String value) {
        if (value == null || !value.startsWith(PREFIX)) {
            throw new IllegalArgumentException("Invalid MeshApp RPC access key prefix");
        }
        byte[] bytes;
        try {
            bytes = DECODER.decode(value.substring(PREFIX.length()));
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid MeshApp RPC access key encoding", e);
        }
        if (bytes.length != KEY_BYTES) {
            throw new IllegalArgumentException("Invalid MeshApp RPC access key length");
        }
        return new RpcAccessKey(value, bytes);
    }

    /**
     * Generates a random challenge nonce.
     *
     * @return base64url nonce
     */
    public static String newNonce() {
        byte[] bytes = new byte[NONCE_BYTES];
        SECURE_RANDOM.nextBytes(bytes);
        return ENCODER.encodeToString(bytes);
    }

    /**
     * @return original key text
     */
    public String value() {
        return value;
    }

    /**
     * Derives a stable external-router room id from the key without revealing
     * the key itself.
     *
     * @return versioned base64url room id
     */
    public String roomId() {
        byte[] digest = hmac(ROOM_ID_CONTEXT);
        return ROOM_ID_PREFIX + ENCODER.encodeToString(digest);
    }

    /**
     * Calculates an HMAC proof for one challenge nonce.
     *
     * @param nonce base64url nonce
     * @return base64url proof
     */
    public String proof(String nonce) {
        return ENCODER.encodeToString(hmac(requireText(nonce, "nonce").getBytes(java.nio.charset.StandardCharsets.UTF_8)));
    }

    /**
     * Verifies a challenge proof in constant time.
     *
     * @param nonce challenge nonce
     * @param proof received proof
     * @return {@code true} when the proof matches this key
     */
    public boolean verify(String nonce, String proof) {
        if (proof == null || proof.isBlank()) {
            return false;
        }
        return MessageDigest.isEqual(proof(nonce).getBytes(java.nio.charset.StandardCharsets.UTF_8),
                proof.trim().getBytes(java.nio.charset.StandardCharsets.UTF_8));
    }

    /**
     * Calculates the client-side authentication proof for encrypted RPC v2.
     *
     * @param serverNonce nonce generated by the host
     * @param clientNonce nonce generated by the remote client
     * @return base64url proof
     */
    public String clientProof(String serverNonce, String clientNonce) {
        return proof(CLIENT_PROOF_CONTEXT, serverNonce, clientNonce);
    }

    /**
     * Verifies the client-side authentication proof for encrypted RPC v2.
     */
    public boolean verifyClientProof(String serverNonce, String clientNonce, String proof) {
        try {
            return verifyProof(clientProof(serverNonce, clientNonce), proof);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    /**
     * Calculates the server-side authentication proof for encrypted RPC v2.
     *
     * @param serverNonce nonce generated by the host
     * @param clientNonce nonce generated by the remote client
     * @return base64url proof
     */
    public String serverProof(String serverNonce, String clientNonce) {
        return proof(SERVER_PROOF_CONTEXT, serverNonce, clientNonce);
    }

    /**
     * Verifies the server-side authentication proof for encrypted RPC v2.
     */
    public boolean verifyServerProof(String serverNonce, String clientNonce, String proof) {
        try {
            return verifyProof(serverProof(serverNonce, clientNonce), proof);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    byte[] keyMaterial() {
        return Arrays.copyOf(keyBytes, keyBytes.length);
    }

    private String proof(byte[] context, String serverNonce, String clientNonce) {
        return ENCODER.encodeToString(hmac(transcript(
                context,
                requireText(serverNonce, "serverNonce"),
                requireText(clientNonce, "clientNonce"))));
    }

    private static boolean verifyProof(String expected, String actual) {
        if (actual == null || actual.isBlank()) {
            return false;
        }
        return MessageDigest.isEqual(
                expected.getBytes(java.nio.charset.StandardCharsets.UTF_8),
                actual.trim().getBytes(java.nio.charset.StandardCharsets.UTF_8));
    }

    private byte[] hmac(byte[] data) {
        Objects.requireNonNull(data, "data");
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(keyBytes, "HmacSHA256"));
            return mac.doFinal(data);
        } catch (Exception e) {
            throw new IllegalStateException("Unable to calculate RPC access key HMAC", e);
        }
    }

    private static String requireText(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " is required");
        }
        return value.trim();
    }

    private static byte[] transcript(byte[] context, String serverNonce, String clientNonce) {
        byte[] server = serverNonce.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        byte[] client = clientNonce.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(context.length + 4 + server.length + 4 + client.length);
        buffer.put(context);
        buffer.putInt(server.length);
        buffer.put(server);
        buffer.putInt(client.length);
        buffer.put(client);
        return buffer.array();
    }
}
